services:
  rabbitmq:
    image: ghcr.io/bhopkinson/orchardhouse-rabbitmq:main
    container_name: rabbitmq
    restart: unless-stopped
    security_opt:  
      - no-new-privileges
    env_file:
      - ../../stack.env
    ports:
      - "1883:1883"
      - "5672:5672"
      - "15672:15672"
      - "15675:15675"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rabbitmq.rule=Host(`rabbitmq.$DOMAIN`)"
      - "traefik.http.routers.rabbitmq.middlewares=traefik-forward-auth"
      - "traefik.http.services.rabbitmq.loadbalancer.server.port=15672"
    networks:
      - network_traefik

  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    restart: unless-stopped
    security_opt:  
      - no-new-privileges
    ports:
      - "5678:5678"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.n8n.rule=Host(`n8n.$DOMAIN`)"
      - "traefik.http.routers.n8n.middlewares=traefik-forward-auth"
    networks:
      - network_traefik
    volumes:
      - n8n_data:/home/node/.n8n

  node-red:
    image: nodered/node-red:latest
    container_name: node-red
    restart: unless-stopped
    security_opt:  
      - no-new-privileges
    environment:
      - TZ=Europe/London
    ports:
      - "1880:1880"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nodered.rule=Host(`nodered.$DOMAIN`)"
      - "traefik.http.routers.nodered.middlewares=traefik-forward-auth"
    networks:
      - network_traefik
    volumes:
      - node-red-data:/data:z
      - home-assistant_config:/home-assistant:ro

  zigbee2mqtt:
    image: koenkk/zigbee2mqtt
    container_name: zigbee2mqtt
    restart: unless-stopped
    security_opt:  
      - no-new-privileges
    privileged: true
    volumes:
      - zigbee2mqtt-data:/app/data:z
      - /run/udev:/run/udev:ro
    #  - /dev:/dev
    ports:
      - 8081:8080
    environment:
      - TZ=Europe/London
    #device_cgroup_rules:
    #  - 'c 188:* rmw'
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    group_add:
      - dialout
    user: 1000:1000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.zigbee2mqtt.rule=Host(`zigbee2mqtt.$DOMAIN`)"
      - "traefik.http.routers.zigbee2mqtt.middlewares=traefik-forward-auth"
    networks:
      - network_traefik

networks:
  default:
    driver: bridge
  network_traefik:
    external: true

volumes:
  n8n_data:
  node-red-data:
  zigbee2mqtt-data:
  home-assistant_config:
    external: true