services:
  rabbitmq:
    image: ghcr.io/bhopkinson/orchardhouse-rabbitmq:main
    container_name: rabbitmq
    restart: unless-stopped
    security_opt:  
      - no-new-privileges
    env_file:
      - ../../stack.env
    ports:
      - "1883:1883"
      - "5672:5672"
      - "15672:15672"
      - "15675:15675"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rabbitmq.rule=Host(`rabbitmq.$DOMAIN`)"
      - "traefik.http.routers.rabbitmq.middlewares=traefik-forward-auth"
      - "traefik.http.services.rabbitmq.loadbalancer.server.port=15672"
    networks:
      - network_traefik

  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    restart: unless-stopped
    security_opt:  
      - no-new-privileges
    ports:
      - "5678:5678"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.n8n.rule=Host(`n8n.$DOMAIN`)"
      - "traefik.http.routers.n8n.middlewares=traefik-forward-auth"
    networks:
      - network_traefik
    volumes:
      - n8n_data:/home/node/.n8n

  node-red:
    image: nodered/node-red:latest
    container_name: node-red
    restart: unless-stopped
    security_opt:  
      - no-new-privileges
    environment:
      - TZ=Europe/London
    ports:
      - "1880:1880"
    networks:
      - network_traefik
    volumes:
      - node-red-data:/data

networks:
  default:
    driver: bridge
  network_traefik:
    external: true

volumes:
  n8n_data:
  node-red-data: