services:
  rabbitmq:
    image: ghcr.io/bhopkinson/orchardhouse-rabbitmq:main
    container_name: rabbitmq
    restart: unless-stopped
    env_file:
      - ../../stack.env
    ports:
      - "1883:1883"
      - "5672:5672"
      - "15672:15672"
      - "15675:15675"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rabbitmq.rule=Host(`rabbitmq.$DOMAIN`)"
      - "traefik.http.routers.rabbitmq.middlewares=traefik-forward-auth"
      - "traefik.http.services.rabbitmq.loadbalancer.server.port=15672"
    networks:
      - network_traefik

  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.n8n.rule=Host(`n8n.$DOMAIN`)"
      - "traefik.http.routers.n8n.middlewares=traefik-forward-auth"
    networks:
      - network_traefik
    volumes:
      - n8n_data:/home/node/.n8n

networks:
  default:
    driver: bridge
  network_traefik:
    external: true

volumes:
  n8n_data: