services:
  home-assistant:
    image: "ghcr.io/home-assistant/home-assistant:2024.5.5"
    container_name: home-assistant
    volumes:
      - config:/config
      - /etc/localtime:/etc/localtime:ro
      # - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    security_opt:  
      - no-new-privileges
    ports:
      - "8123:8123"
    networks:
      - network_traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.home-assistant.rule=Host(`home-assistant.$DOMAIN`)"
      - "traefik.http.routers.home-assistant.middlewares=traefik-forward-auth"
      - "traefik.http.services.home-assistant.loadbalancer.server.port=8123"

volumes:
  config:

networks:
  # ipvlan:
  #   driver: ipvlan
  #   driver_opts:
  #     parent: $NETWORK_INTERFACE
  #   ipam:
  #     config:
  #     - subnet: $SUBNET
  #       gateway: $GATEWAY
  network_traefik:
    external: true