services:
  home-assistant:
    image: "ghcr.io/home-assistant/home-assistant:2024.5.5"
    container_name: home-assistant
    volumes:
      - config:/config:z
      - /etc/localtime:/etc/localtime:ro
      # - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    security_opt:  
      - no-new-privileges
    ports:
      - "8123:8123"
    networks:
      - network_traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.home-assistant.rule=Host(`ha.$DOMAIN`)"
      - "traefik.http.routers.home-assistant.priority=1"
      - "traefik.http.routers.home-assistant.middlewares=traefik-forward-auth"
      - "traefik.http.routers.home-assistant-webhooks.rule=Host(`ha.$DOMAIN`) && PathPrefix(`/api/webhook/$WEBHOOK_STR`)"
      - "traefik.http.routers.home-assistant-webhooks.priority=2"
      - "traefik.http.middlewares.home-assistant-webhooks.stripprefix.prefixes=/api/webhook/$WEBHOOK_STR"
      - "traefik.http.services.home-assistant.loadbalancer.server.port=8123"

  influxdb:
    image: influxdb:2
    container_name: influxdb
    volumes:
      - influxdb-config:/etc/influxdb2
      - influxdb-data:/var/lib/influxdb2
    restart: unless-stopped
    security_opt:
      - no-new-privileges
    ports:
      - 8086:8086
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_ORG=Orchard House
      - DOCKER_INFLUXDB_INIT_BUCKET=Home Assistant
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
    networks:
      - network_traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.influxdb.rule=Host(`influxdb.$DOMAIN`)"
      - "traefik.http.routers.influxdb.middlewares=traefik-forward-auth"
      - "traefik.http.services.influxdb.loadbalancer.server.port=8086"

volumes:
  config:
  influxdb-config:
  influxdb-data:

networks:
  # ipvlan:
  #   driver: ipvlan
  #   driver_opts:
  #     parent: $NETWORK_INTERFACE
  #   ipam:
  #     config:
  #     - subnet: $SUBNET
  #       gateway: $GATEWAY
  network_traefik:
    external: true
