services:
  traefik:
    image: traefik:v3.0
    container_name: "traefik"
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    depends_on:
      - socket_proxy
    command:
      - "--log.level=DEBUG"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.endpoint=tcp://socket-proxy:2375"
      - "--providers.docker.exposedbydefault=false"
      # Listeners
      # - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      # - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      # - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      # TLS configuration
      - "--entrypoints.websecure.http.tls=true"
      - "--entrypoints.websecure.http.tls.certresolver=default"
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    labels:
       - "traefik.enable=true"
       - "traefik.http.routers.dashboard.rule=Host(`traefik.$DOMAIN`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
       - "traefik.http.routers.dashboard.service=api@internal"
       - "traefik.http.routers.dashboard.middlewares=traefik-forward-auth"
    networks:
      - traefik
      - cloudflared
      - socket_proxy

  cloudflared:
    image: cloudflare/cloudflared
    container_name: cloudflared
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARED_TUNNEL_TOKEN}
    networks:
      - cloudflared

  cloudflare-companion:
    image: tiredofit/traefik-cloudflare-companion
    container_name: cloudflare-companion
    security_opt:
      - no-new-privileges:true
    depends_on:
      - socket_proxy
    environment:
      - DOCKER_HOST=tcp://socket-proxy:2375
      - TIMEZONE=Europe/London
      - LOG_TYPE=CONSOLE
      - LOG_LEVEL=INFO
      - RC_TYPE=CNAME
      - CF_TOKEN=${CLOUDFARE_DNS_API_TOKEN}
      - TARGET_DOMAIN=${DOMAIN}
      - REFRESH_ENTRIES=TRUE
      - DOMAIN1=${DOMAIN}
      - DOMAIN1_ZONE_ID=${DOMAIN_CLOUDFLARE_ZONE_ID}
      - DOMAIN1_PROXIED=TRUE
    restart: unless-stopped
    networks:
      - socket_proxy

  traefik-forward-auth:
    container_name: traefik-forward-auth
    image: thomseddon/traefik-forward-auth:latest
    security_opt:
      - no-new-privileges:true
    depends_on:
      - traefik
    networks:
      - traefik
    environment:
      - DEFAULT_PROVIDER=oidc
      - PROVIDERS_OIDC_ISSUER_URL=$OIDC_ISSUER_URL
      - PROVIDERS_OIDC_CLIENT_ID=$OIDC_CLIENT_ID
      - PROVIDERS_OIDC_CLIENT_SECRET=$OIDC_CLIENT_SECRET
      - COOKIE_DOMAIN=$DOMAIN
      - AUTH_HOST=auth.$DOMAIN
      - SECRET=$FORWARD_AUTH_SECRET
      - LOG_LEVEL=debug
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-forward-auth.rule=Host(`auth.$DOMAIN`)"
      - "traefik.http.routers.traefik-forward-auth.middlewares=traefik-forward-auth"
      - "traefik.http.services.traefik-forward-auth.loadbalancer.server.port=4181"
      - "traefik.http.middlewares.traefik-forward-auth.forwardauth.address=http://traefik-forward-auth:4181"
      - "traefik.http.middlewares.traefik-forward-auth.forwardauth.trustForwardHeader=true"
      - "traefik.http.middlewares.traefik-forward-auth.forwardauth.authResponseHeaders=X-Forwarded-User"
    restart: unless-stopped

  omada-controller:
    image: mbentley/omada-controller:5.13
    container_name: "omada-controller"
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    environment:
      - MANAGE_HTTP_PORT=8088
      - MANAGE_HTTPS_PORT=8043
      - PORTAL_HTTP_PORT=8088
      - PORTAL_HTTPS_PORT=8843
      - PORT_APP_DISCOVERY=27001
      - PORT_ADOPT_V1=29812
      - PORT_UPGRADE_V1=29813
      - PORT_MANAGER_V1=29811
      - PORT_MANAGER_V2=29814
      - PORT_DISCOVERY=29810
      - PORT_TRANSFER_V2=29815
      - PORT_RTTY=29816
    ulimits:
      nofile:
        soft: 4096
        hard: 8192
    stop_grace_period: 60s
    ports:
      - "8088:8088"
      - "8043:8043"
      - "8843:8843"
      - "27001:27001/udp"
      - "29810:29810/udp"
      - "29811-29816:29811-29816"
    volumes:
      - omada-data:/opt/tplink/EAPController/data
      - omada-logs:/opt/tplink/EAPController/logs
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.omada-controller.rule=Host(`omada.$DOMAIN`)"
      - "traefik.http.routers.omada-controller.middlewares=traefik-forward-auth"
      - "traefik.http.services.omada-controller.loadbalancer.server.port=8088"
    networks:
      - traefik

  socket-proxy:
    image: tecnativa/docker-socket-proxy
    container_name: socket-proxy
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      socket_proxy:
    ports:
      - "127.0.0.1:2375:2375"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - LOG_LEVEL=info
      - CONTAINERS=1 # traefik, cloudflare-companion

volumes:
  omada-data:
  omada-logs:

networks:
  traefik:
  cloudflared:
  socket_proxy: