version: '3.3'

services:
  traefik:
    image: traefik:v2.11
    container_name: "traefik"
    restart: unless-stopped
    command:
      - "--log.level=DEBUG"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.websecure.http.tls.domains[0].main=$DOMAIN"
      - "--entrypoints.websecure.http.tls.domains[0].sans=*.$DOMAIN"
      - "--entrypoints.websecure.http.tls.certresolver=default"
      #- "--entrypoints.websecure.http.tls.certresolver=myresolver"
      - "--entrypoints.websecure.http.middlewares=traefik-forward-auth"
      - "--certificatesresolvers.myresolver.acme.dnschallenge=true"
      - "--certificatesresolvers.myresolver.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.myresolver.acme.email=$EMAIL"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - letsencrypt:/letsencrypt
    labels:
      - "traefik.enable=true"
      # - "traefik.http.routers.dashboard.rule=Host(`traefik.localhost`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      # - "traefik.http.routers.dashboard.service=api@internal"
      # - "traefik.http.routers.dashboard.middlewares=forward-auth"
      # - "traefik.http.middlewares.auth.basicauth.users=$TRAEFIK_USER_PASS"
      # - "traefik.http.middlewares.auth.forwardauth.address=http://forward-auth:4181"
      # - "traefik.http.middlewares.auth.forwardauth.trustForwardHeader=true"
      # - "traefik.http.middlewares.auth.forwardauth.authResponseHeaders=X-Forwarded-User"
    environment:
      - "CF_API_EMAIL=$CF_API_EMAIL"
      - "CF_API_KEY=$CLOUDFARE_DNS_API_TOKEN"
    networks:
      - traefik
      - cloudflared

  cloudflared:
    image: cloudflare/cloudflared
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARED_TUNNEL_TOKEN}
    networks:
      - cloudflared

  cloudflare-companion:
    image: tiredofit/traefik-cloudflare-companion
    container_name: cloudflare-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TIMEZONE=Europe/London
      - LOG_TYPE=CONSOLE
      - LOG_LEVEL=INFO
      - RC_TYPE=CNAME
      - CF_TOKEN=${CLOUDFARE_DNS_API_TOKEN}
      - TARGET_DOMAIN=${DOMAIN}
      - REFRESH_ENTRIES=TRUE
      - DOMAIN1=${DOMAIN}
      - DOMAIN1_ZONE_ID=${DOMAIN_CLOUDFLARE_ZONE_ID}
      - DOMAIN1_PROXIED=TRUE
    restart: unless-stopped

  traefik-forward-auth:
    container_name: traefik-forward-auth
    image: thomseddon/traefik-forward-auth:latest
    depends_on:
      - traefik
    networks:
      - traefik
    environment:
      - DEFAULT_PROVIDER=oidc
      - PROVIDERS_OIDC_ISSUER_URL=$OIDC_ISSUER_URL
      - PROVIDERS_OIDC_CLIENT_ID=$OIDC_CLIENT_ID
      - PROVIDERS_OIDC_CLIENT_SECRET=$OIDC_CLIENT_SECRET
      - COOKIE_DOMAIN=$DOMAIN
      - AUTH_HOST=auth.$DOMAIN
      - INSECURE_COOKIE=true
      - SECRET=$FORWARD_AUTH_SECRET
      - LOG_LEVEL=debug
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-forward-auth.rule=Host(`auth.$DOMAIN`)"
      - "traefik.http.services.traefik-forward-auth.loadbalancer.server.port=4181"
      - "traefik.http.middlewares.traefik-forward-auth.forwardauth.address=http://traefik-forward-auth:4181"
      - "traefik.http.middlewares.traefik-forward-auth.forwardauth.trustForwardHeader=true"
      - "traefik.http.middlewares.traefik-forward-auth.forwardauth.authResponseHeaders=X-Forwarded-User"
      # - "traefik.http.middlewares.auth-https-redirect.redirectscheme.scheme=https"
      # - "traefik.http.routers.auth.middlewares=auth-https-redirect"
      # - "traefik.http.routers.auth-secure.entrypoints=https"
      # - "traefik.http.routers.auth-secure.rule=Host(`aad.[subdomain.example.com]`)"
      # - "traefik.http.routers.auth-secure.tls=true"
      # - "traefik.http.routers.auth-secure.service=auth"
      # - "traefik.docker.network=traefik"
    restart: unless-stopped

  omada-controller:
    image: mbentley/omada-controller:5.13
    container_name: "omada-controller"
    restart: unless-stopped
    environment:
      - MANAGE_HTTP_PORT=8088
      - MANAGE_HTTPS_PORT=8043
      - PORTAL_HTTP_PORT=8088
      - PORTAL_HTTPS_PORT=8843
      - PORT_APP_DISCOVERY=27001
      - PORT_ADOPT_V1=29812
      - PORT_UPGRADE_V1=29813
      - PORT_MANAGER_V1=29811
      - PORT_MANAGER_V2=29814
      - PORT_DISCOVERY=29810
      - PORT_TRANSFER_V2=29815
      - PORT_RTTY=29816
    ulimits:
      nofile:
        soft: 4096
        hard: 8192
    stop_grace_period: 60s
    ports:
      - "8088:8088"
      - "8043:8043"
      - "8843:8843"
      - "27001:27001/udp"
      - "29810:29810/udp"
      - "29811-29816:29811-29816"
    volumes:
      - omada-data:/opt/tplink/EAPController/data
      - omada-logs:/opt/tplink/EAPController/logs
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`omada.localhost`)"
      - "traefik.http.routers.omada-controller.entrypoints=web"
      - "traefik.http.services.omada-controller.loadbalancer.server.port=8088"

  whoami:
    image: "traefik/whoami"
    container_name: "whoami"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.$DOMAIN`)"
      - "traefik.http.routers.external.entrypoints=websecure"
      - "traefik.http.routers.external.tls=true"
    networks:
      - traefik

volumes:
  omada-data:
  omada-logs:
  letsencrypt:

networks:
  traefik:
  cloudflared: