version: '3'

services:
  portainer:
    image: portainer/portainer
    container_name: portainer2
    ports:
      - "8001:8000"
      - "9444:9443"
    command: -H unix:///var/run/docker.sock
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - data:/data

volumes:
  data: