version: '3'

services:
  portainer:
    image: portainer/portainer-ee:latest
    container_name: portainer2
    ports:
      - "8001:8000"
      - "9444:9443"
    restart: always
    network_mode: bridge