services:
  whoami:
    image: "traefik/whoami"
    container_name: "whoami"
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.$DOMAIN`)"
      - "traefik.http.routers.whoami.middlewares=traefik-forward-auth"
      # - "traefik.http.routers.whoamilocal.rule=Host(`whoami.local`)"
    networks:
      - network_traefik

  mqttx:
    image: "emqx/mqttx-web"
    container_name: "mqttx"
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    ports:
      - "81:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mqttx.rule=Host(`mqttx.$DOMAIN`)"
      - "traefik.http.routers.mqttx.middlewares=traefik-forward-auth"
    networks:
      - network_traefik

  filebrowser:
    image: "filebrowser/filebrowser:v2"
    container_name: "filebrowser"
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    environment:
      - FB_NOAUTH=true
    volumes:
      - home-assistant_config:/srv/home-assistant:z
      - automation_node-red-data:/srv/node-red:z
      - automation_zigbee2mqtt-data:/srv/zigbee2mqtt:z
    ports:
      - 82:80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.filebrowser.rule=Host(`files.$DOMAIN`)"
      - "traefik.http.routers.filebrowser.middlewares=traefik-forward-auth"
    networks:
      - network_traefik

  vscode:
    image: "lscr.io/linuxserver/code-server"
    container_name: "vscode"
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    volumes:
      - vscode_config:/config
      - home-assistant_config:/home-assistant:z
      - automation_zigbee2mqtt-data:/zigbee2mqtt:z
    ports:
      - 8443:8443
    environment:
      # - PUID=1000
      # - PGID=1000
      - TZ=Etc/GB
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.code.rule=Host(`code.$DOMAIN`)"
      - "traefik.http.routers.code.middlewares=traefik-forward-auth"
    networks:
      - network_traefik  

networks:
  network_traefik:
    external: true

volumes:
  home-assistant_config:
    external: true
  automation_node-red-data:
    external: true
  automation_zigbee2mqtt-data:
    external: true
  vscode_config: