services:
  whoami:
    image: "traefik/whoami"
    container_name: "whoami"
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.$DOMAIN`)"
      - "traefik.http.routers.whoami.middlewares=traefik-forward-auth"
      # - "traefik.http.routers.whoamilocal.rule=Host(`whoami.local`)"
    networks:
      - network_traefik

  mqttx:
    image: "emqx/mqttx-web"
    container_name: "mqttx"
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    ports:
      - "81:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mqttx.rule=Host(`mqttx.$DOMAIN`)"
      - "traefik.http.routers.mqttx.middlewares=traefik-forward-auth"
    networks:
      - network_traefik

  filebrowser:
    image: "filebrowser/filebrowser:v2"
    container_name: "filebrowser"
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    command:
      - "config init"
      - "config set --auth.method=noauth"
    volumes:
      - home-assistant_config:/srv/home-assistant:z
    ports:
      - 82:80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.filebrowser.rule=Host(`files.$DOMAIN`)"
      - "traefik.http.routers.filebrowser.middlewares=traefik-forward-auth"
    networks:
      - network_traefik

networks:
  network_traefik:
    external: true

volumes:
  home-assistant_config:
    external: true